name: Build and deploy .NET Core app to Azure Container App app-bancodeitens-api

on:
  push:
    branches:
      - master # O branch que você está enviando o código
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Jose-Marcello/bancodeitens_backend
          ref: master # O branch a ser monitorado

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: acrbancodeitensdev.azurecr.io # Seu ACR Name
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: BancoDeItensWebApi # O caminho da subpasta do projeto
          containerAppName: app-bancodeitens-api
          resourceGroup: rg-banco-itens-dev
          acrName: acrbancodeitensdev
          imageToBuild: acrbancodeitensdev.azurecr.io/app-bancodeitens-api:${{ github.sha }}
          # Use o Dockerfile que você criou na subpasta:
          dockerfilePath: BancoDeItensWebApi/Dockerfile 
          targetPort: 8080
          ingress: external