name: Backend - Build & Deploy Docker Image (GHCR)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  build_push_and_deploy:
    runs-on: ubuntu-latest
    name: Build, Push to GHCR, and Trigger Deploy
    
    # Permissões necessárias para interagir com o GitHub Container Registry
    permissions:
      contents: read
      packages: write # Permite push para o GitHub Container Registry

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # -----------------------------------------------------------
      # 1. Autenticação no GitHub Container Registry (GHCR)
      # O GITHUB_TOKEN é injetado automaticamente pelo GitHub Actions
      # -----------------------------------------------------------
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Define o nome da imagem
      - name: Define Image Name
        id: image_name
        run: |
          # Substitua 'bancodeitens-api' pelo nome do seu projeto de backend se for diferente
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/bancodeitens-api
          # Limpar para minúsculas
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          # Usa o commit SHA como tag única
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
      # -----------------------------------------------------------
      # 2. Build da Imagem Docker (Usando o Dockerfile existente)
      # -----------------------------------------------------------
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.image_name.outputs.IMAGE_ID }}:latest
            ${{ steps.image_name.outputs.IMAGE_ID }}:${{ steps.image_name.outputs.VERSION }}
          # Assume que o Dockerfile está na raiz do repositório
          file: ./Dockerfile 

      # -----------------------------------------------------------
      # 3. Deploy/Trigger no Novo Provedor (Render ou Railway)
      # Este passo será substituído pela API ou Webhook do Render
      # -----------------------------------------------------------
      - name: Trigger Render Deployment (Placeholder)
        run: echo "Substitua este passo pela chamada de API ou Webhook do Render"